requirements.txt
server.py

Running: 
`pip install -r requirements.txt`
then 
`python server.py` 
will give you a server running at localhost:5000

Flask Skeleton with requirements.txt

---

models.py

Product model created with just init that has: id, name, price and description

Creating models.py for flask app that includes the product model.

---

shopcart.py

Add the class Shopcart to data model

Add the data model of Shopcart

---

requirements.txt
server.py
setup.cfg
tests/test_product.py
tests/test_server.py
tests/test_shopcart.py

This PR adds the required setup for TDD in python.
Tests are written using `unittest`, `Mock`, and `MagicMock`. All are included in Python3.
Our test runner is `nose` and we are displaying code coverage via `coverage`.
There are 3 `TestCase` classes to get us up and running:
* `test_product.py`
* `test_shopcart.py`
* `test_server.py`
```
nosetests
```
```
coverage report -m
```

Add testing setup and requirements

---

models/shopcart.py
tests/test_shopcart.py

* Added `save()` method and class-level `remove_all()` and `all()` methods to `shopcart.py`
* Added `test_it_can_be_saved()` and `setUp()` methods to `test_shopcart.py` 
After checking out the `create_shopcart` branch: 
`vagrant ssh`
`cd /vagrant`
`nosetests`
All 4 test cases should pass.

Create & Save Shopcart

---

tests/test_shopcart.py

I technically already implemented this method in #30 so all I had to do was create a unit test in `test_shopcart.py` 
`vagrant ssh`
`cd /vagrant`
`nosetests` 
5 test cases should pass

List all Shopcarts

---

server.py
tests/test_server.py

Adding a basic description to the root.
Modified the test_index accordingly.

Adding basic description to the root

---

models/shopcart.py
tests/test_shopcart.py

Added a `delete` instance method in `shopcart.py` and a corresponding unit test in `test_shopcart.py` 
Running `nosetests` should have all 6 test cases pass

Delete a Single Shopcart

---

models/shopcart.py
tests/test_shopcart.py

Adds `find` static method to `Shopcart`. Returns `shopcart` instance if found, otherwise `None`.
All tests passing and keeps 100% code coverage.

Add find method to shopcart

---

models/shopcart.py
server.py
tests/test_server.py

Made a GET handler in `server.py` for retrieving a shopcart with a given id, and the corresponding unit test in `test_server.py`
All 16 test cases should pass

View Shopcart - API

---

models/shopcart.py
server.py
tests/test_server.py
tests/test_shopcart.py

PUT On /shopcarts/uid/products/pid
All tests in place.
Coverage of 98%
Added utility function from rofrano's code to check for media type.

Updating product quant in shopcarts PUT 

---

models/shopcart.py
server.py
tests/test_server.py
tests/test_shopcart.py

Impements find_product in the model for the query.
Get on /shopcarts
Test should pass with 98% coverage

Query product id 

---

Vagrantfile

* Checkout the branch `cf-vagrant`
* `vagrant up`
* `vagrant ssh`
* Run `bx` and `cf` to check that they're installed correctly

Added Bluemix CLI to vagrantfile

---

Vagrantfile
requirements.txt

* Issue `vagrant up` & `vagrant ssh`
* Run `mysql -uroot -proot -P 3306 -h 172.17.0.2` to drop into the MySQL shell

added docker container running mysql using vagrantfile

---

README.md

* Added running/installation instructions
* Added testing instructions
* Added overview of our RESTful API
I wasn't sure how detailed to get for the API, so feel free to modify whatever

Updated readme with project info

---

app/models/shopcart.py
app/server.py
requirements.txt
tests/test_product.py
tests/test_server.py
tests/test_shopcart.py

This adds persistence for the `Shopcart` model. All tests passing and coverage is 100%.

Add Shopcart persistence

---

features/shopcarts.feature
features/steps/shopcart_steps.py

This adds the scenario as described in the title.
All behave tests passing.

Add scenario for deleting a product from a shopcart

---

app/server.py

1localhost:5000/apidocs/index.html1 will show Delete a Shopcart docs

Flassger Delete a Shopcart

---

app/server.py

localhost:5000/apidocs/index.html will show Reset shopcarts docs

Flassger Reset Shopcarts

---

app/server.py

`localhost:5000/apidocs/index.html` will show Prune shopcarts docs

Flassger Prune Shopcarts

---

app/server.py

Added documentation to get a shopcart.
Feel free to modify or add things.

swagger of get shopcart/id

---

app/models/shopcart.py
app/server.py
features/shopcarts.feature
features/steps/shopcart_steps.py
tests/test_server.py
tests/test_shopcart.py

nosetests and behave pass completely.
I think we don't have the database problem anymore. I was able to run behave on all the tests many times.

Flassger add product & update the app

---

app/server.py

Flassger for delete a product and fixed an id from add product.

delete a product & fixed a thing in add product
